---
- name: Setup and Run Spring Boot Application
  hosts: web_servers
  become: false # ec2-userで実施
  gather_facts: false

  vars:
    repo_url: https://github.com/koujienami/aws-study.git
    app_dir: "/home/ec2-user/aws-study"

  tasks:
    # 1. JavaとGitとMySQL(MariaDB)をインストール
    - name: Install Java21 Git MySQL
      ansible.builtin.dnf:
        name: 
         - java-21-amazon-corretto-devel.x86_64
         - git
         - mariadb105 # mysqlコマンドがこれに含まれる
        state: present
      become: true # sudo権限で実施

    # 2. リポジトリをダウンロード
    - name: Clone the repoitory
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
      become: true
    
    # 3. 実行権限の付与
    - name: Grant execute permission to gradlew
      ansible.builtin.file :
        path: "{{ app_dir }}/gradlew"
        mode: '0755'
    
    # 4. テンプレートを使って設定ファイルを上書き生成する
    - name: Deploy application.properties from template
      ansible.builtin.template:
        src: templates/application.properties.j2
        dest: "{{ app_dir }}/src/main/resources/application.properties"
        mode: '0644'
        no_log: true # 実行ログにパスワード等を表示しない
    
    # 5. データベースに情報を書き込む
    - name: Import SQL to RDS
      ansible.builtin.shell: >
        mysql -h {{ rds_endpoint }} -u {{ db_user }} -p{{ db_password }} {{ db_name }}
        < {{ app_dir }}/src/main/resources/create.sql

    # 6. Spring Bootを使う準備
    - name: Build application with Gradle
      ansible.builtin.command: ./gradlew build -x test
      args:
        chdir: "{{ app_dir }}"
      changed_when: false # buildするだけで特に何も変わらないので
    
    # 7. serviceファイルの配置
    - name: Deploy Systemd service file
      ansible.builtin.template:
        src: templates/springapp.service.j2
        dest: /etc/systemd/system/springapp.service # 要確認
        mode: '0644'
      notify: Reload systemd # ファイルが変わったらdaemon-reloadを呼ぶ
      become: true # sudo権限で実施
    
    # 8. Spring Bootを起動して有効化する
    - name: Start and Enable Spring Boot service
      ansible.builtin.systemd_service:
        name: springapp
        state: restarted # 常に最新のビルドで再起動
        enabled: true     # OS起動時の自動起動を有効化
      become: true

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true # serviceファイルの変更を読み取る