name: "Ansible Deploy"

on: 
  workflow_run:
    workflows: [Terraform Plan & Apply]
    types: completed

permissions:
  id-token: write
  contents: read

jobs: 
  ansible-deploy:
    name: Ansible deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Chcekout
        uses: actions/checkout@v4

      # 1. 前のWorkflowで作られたinventory.iniをダウンロード
      - name: Download inventory
        uses: actions/download-artifact@v5
        with:
          name: ansible-inventory
          path: ansible/inventory/ # ansibleフォルダの中に配置
          # 別のWorkflowから取得するための設定
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: check inventory
        run: cat ansible/inventory/inventory.ini

      # 2. AWS認証 (SSM接続に必要)    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      
      # 3. 実行環境のセットアップ
      - name: Install Ansible and AWS collection
        run: |
         pip install ansible botocore boto3

      # 4. SSM経由で接続するための設定
      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      # 5. 構文チェック (Syntax Check)
      - name: Ansible Syntax Check
        working-directory: ansible
        run: |
          ansible-playbook playbooks/playbook.yml --syntax-check

      # 6. ドライラン (Check Mode)
      #- name: Ansible Dry Run
        #working-directory: ansible
        #env:
          #ANSIBLE_CONFIG: ${{ github.workspace }}/ansible/ansible.cfg
          #AWS_REGION: ap-northeast-1 # プラグイン（boto3）の安定動作のために必須
        #run: |
          #ansible-playbook playbooks/playbook.yml --check

      # 7. Ansible実行（本番）    
      - name: Run Playbook
        working-directory: ansible
        env:
          ANSIBLE_CONFIG: ${{ github.workspace }}/ansible/ansible.cfg #明示的に
          AWS_REGION: ap-northeast-1 # プラグイン（boto3）の安定動作のために必須
        run: |
         ansible-playbook playbooks/playbook.yml -vv \
           --extra-vars "rds_endpoint=${{ secrets.RDS_ENDPOINT }} \
                         db_user=${{ secrets.RDS_MASTER_USER_NAME }} \
                         db_password=${{ secrets.RDS_MASTER_USER_PASSWORD }} \
                         db_name=${{ secrets.RDS_DB_NAME }}"
