name: "Ansible deploy & Java install"

on: 
  workflow_run:
    workflows: [Terraform Plan & Apply]
    types: completed

permissions:
  id-token: write
  contents: read

jobs: 
  ansible-deploy:
    name: Ansible deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Chcekout
        uses: actions/checkout@v4

      # 1. 前のWorkflowで作られたinventory.iniをダウンロード
      - name: Download inventory
        uses: actions/download-artifact@v5
        with:
          name: ansible-inventory
          path: ansible/inventory/ # ansibleフォルダの中に配置
          # 別のWorkflowから取得するための設定
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # 2. AWS認証 (SSM接続に必要)    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
     
      # 3. 実行環境のセットアップ
      - name: Install Ansible and AWS collection
        run: |
          pip install ansible botocore boto3
          ansible-galaxy collection install amazon.aws

      - name: Check ansible
        run: which ansible-playbook || true

      - name: Check ansible ver
        run: ansible --version

      - name: Check installed collections ansible
        run: ansible-galaxy collection list | grep amazon.aws
     
      - name: Check installed collections python
        run: pip show boto3

      # 4。SSM経由で接続するための設定
      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb
      
      - name: Check session-manager-plugin
        run: |
         session-manager-plugin --version

      - name: Debug inventory vars
        working-directory: ansible
        run: |
          ansible-inventory --list
      
      - name: Check inventory
        working-directory: ansible
        run: |
          ansible-inventory -i inventory/inventory.ini --list -y
          
      - name: Check plugin
        working-directory: ansible
        run: |
          ansible-inventory -i inventory/inventory.ini --host i-056e64213c274e46a

      - name: Check plugin2
        working-directory: ansible
        run: |
          ansible-playbook -i inventory/inventory.ini playbooks/playbook.yml -vvvv

      - name: Check SSM managed instance
        run: |
         aws ssm describe-instance-information \
           --query "InstanceInformationList[].InstanceId"
      
      # 5. Ansible実行    
      - name: Run Playbook
        working-directory: ansible
        run: |
          ansible-playbook playbooks/playbook.yml